# https://github.com/shivammathur/setup-php
name: Tests

on: [ push ]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest

        # Docs: https://docs.github.com/en/actions/using-containerized-services
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: symfony
                    MYSQL_DATABASE: mfagp_test
                ports:
                    - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --name=mysql

        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    tools: phpunit-bridge
                    extensions: mbstring, xml, ctype, iconv, json, mysql
                    ini-values: date.timezone=Europe/Paris
            -   uses: actions/checkout@v4
            -   name: Create empty firebase-credentials.json
                run: mkdir -p var && cp tests/Resources/fake-firebase-credentials.json var/firebase-credentials.json
            -   name: Composer cache
                id: cache-vendor
                uses: actions/cache@v4
                with:
                    path: vendor
                    key: composer-${{ hashFiles('**/composer.lock') }}
            -   name: Composer install
                if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            -   name: Run Migration
                run: php bin/console doctrine:migrations:migrate --no-interaction
                env:
                    DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/mfagp_test
                    DB_NAME_SUFFIX: ''
            -   name: Execute tests (Unit and Feature tests) via PHPUnit
                run: vendor/bin/phpunit
                env:
                    DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/mfagp_test
                    DB_NAME_SUFFIX: ''
            #-   name: phpstan
            #    if: always()
            #    run: composer phpstan
            -   name: composer validate
                if: always()
                run: composer validate --strict
            -   name: lint:container
                if: always()
                run: php bin/console lint:container
            -   name: lint:twig
                if: always()
                run: php bin/console lint:twig templates
            -   name: lint:yaml
                if: always()
                run: php bin/console lint:yaml config src
            -   name: doctrine:schema:validate
                if: always()
                run: php bin/console doctrine:schema:validate
                env:
                    DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/mfagp_test
                    DB_NAME_SUFFIX: ''
